use std::fs;
use std::path::PathBuf;

use crate::url::ParsedUrl;

/// Write received Set-Cookie headers to a Netscape-format cookie jar file.
///
/// The per-cookie line format is:
/// `<domain>\tTRUE\t<path>\t<secure>\t<expires>\t<name>\t<value>`
///
/// HttpOnly cookies get the `#HttpOnly_` prefix on the domain column.
pub(crate) fn save_cookie_jar(
    path: &PathBuf,
    url: &ParsedUrl,
    request_host: &str,
    headers: &[(String, String)],
) {
    let cookies: Vec<&str> = headers
        .iter()
        .filter(|(k, _)| k == "set-cookie")
        .map(|(_, v)| v.as_str())
        .collect();

    let mut lines = vec![
        "# Netscape HTTP Cookie File".to_string(),
        "# https://curl.se/docs/http-cookies.html".to_string(),
        "# This file was generated by libcurl! Edit at your own risk.".to_string(),
        String::new(),
    ];

    for cookie in cookies {
        if let Some(line) = format_cookie_line(cookie, url, request_host) {
            lines.push(line);
        }
    }

    let _ = fs::write(path, lines.join("\n") + "\n");
}

pub(crate) fn format_cookie_line(
    cookie: &str,
    url: &ParsedUrl,
    request_host: &str,
) -> Option<String> {
    let mut parts = cookie.split(';');
    let name_value = parts.next()?.trim();
    let (name, value) = name_value.split_once('=')?;

    let mut domain: Option<String> = None;
    let mut path: String = "/".to_string();
    let mut secure = false;
    let mut http_only = false;
    let mut expires: i64 = 0;
    let mut domain_explicit = false;

    for part in parts {
        let part = part.trim();
        let (key, val) = part
            .split_once('=')
            .map_or((part, ""), |(k, v)| (k.trim(), v.trim()));
        match key.to_ascii_lowercase().as_str() {
            "domain" => {
                domain = Some(val.to_string());
                domain_explicit = true;
            }
            "path" => path = val.to_string(),
            "secure" => secure = true,
            "httponly" => http_only = true,
            "max-age" => {
                if let Ok(n) = val.parse::<i64>() {
                    let now = std::time::SystemTime::now()
                        .duration_since(std::time::UNIX_EPOCH)
                        .map(|d| d.as_secs() as i64)
                        .unwrap_or(0);
                    expires = now + n;
                }
            }
            _ => {}
        }
    }

    // Domain: if Set-Cookie didn't specify one, use the request host without leading dot.
    let domain_field = match domain {
        Some(d) if !d.is_empty() => {
            // Netscape format's domain field always has the leading dot when the
            // cookie was issued with an explicit domain attribute.
            if d.starts_with('.') {
                d
            } else {
                format!(".{d}")
            }
        }
        _ => request_host.to_string(),
    };

    let include_subdomains = if domain_explicit { "TRUE" } else { "FALSE" };
    let secure_field = if secure { "TRUE" } else { "FALSE" };
    let prefix = if http_only { "#HttpOnly_" } else { "" };
    let _ = url; // request_host already incorporates the relevant info

    Some(format!(
        "{prefix}{domain_field}\t{include_subdomains}\t{path}\t{secure_field}\t{expires}\t{}\t{}",
        name.trim(),
        value.trim(),
    ))
}
