use std::fs;
use std::path::PathBuf;

use crate::url::ParsedUrl;

pub(crate) fn save_cookie_jar(path: &PathBuf, url: &ParsedUrl, headers: &[(String, String)]) {
    let cookies: Vec<&str> = headers
        .iter()
        .filter(|(k, _)| k == "set-cookie")
        .map(|(_, v)| v.as_str())
        .collect();

    if cookies.is_empty() {
        return;
    }

    let mut lines = Vec::new();
    lines.push("# Netscape HTTP Cookie File".to_string());
    lines.push("# This file was generated by rust-curl".to_string());

    for cookie in cookies {
        let parts: Vec<&str> = cookie.split(';').collect();
        if let Some((name, value)) = parts[0].split_once('=') {
            let domain = url.host.clone();
            let path = "/";
            let secure = cookie.to_lowercase().contains("secure");
            let expire = "0";
            lines.push(format!(
                "{domain}\tTRUE\t{path}\t{}\t{expire}\t{}\t{}",
                if secure { "TRUE" } else { "FALSE" },
                name.trim(),
                value.trim()
            ));
        }
    }

    let _ = fs::write(path, lines.join("\n") + "\n");
}
